### ISSUE TITLE
Always display map in form, with nearby polling place markers if user's location is not selected

### ISSUE THREAD

**Issue by brooksn** [abustamam/polling-place-accessibility#16]

**Comment by brooksn** [comment]
Right now, the map shows most of the survey sites (~~can’t remember why, but~~ a very few sites may have had ~~dirty data~~ missing coordinates), but the markers are wiped when you submit the form and get ​_your_​ polling place displayed. I’m going to work on adding/changing color of ​_your polling place_​ marker on form submission, while keeping all the other markers on the map too.

**Comment by abustamam** [comment]
https://github.com/abustamam/polling-place-accessibility/blob/layout-test/src/datasets/locations.js

Has chords of the two locations that did not have chords in the data
