### ISSUE TITLE
Need clear sample data

### ISSUE THREAD

**Issue by hanschun** [abustamam/polling-place-accessibility#21]
I think we need sample data to populate the form on load. If we pre-fill these fields I think it will be the easiest and quickest to demo. We can just add some sample data as a variable so it is easy to remove later.

**Comment by brooksn** [comment]
There are some good sample addresses/DOBs that work. Let me know if you can't find them.

**Comment by brooksn** [comment]
https://github.com/abustamam/polling-place-accessibility/wiki/Test-Addresses-and-Dates-of-Birth
